run:
  skip-dirs:
    - algorithms
    - testdata
    - static
linters:
  enable-all: true
  disable:
    - bodyclose
    - depguard
    - dogsled
    - gocritic
    - godox
    - gochecknoglobals
    - gochecknoinits
    - wsl
  fast: false
