version: '3.7'
services:
  go:
    image: golang:1.13.1
    volumes:
      - .:/go/src/ants
    ports:
      - 12301:12301
    working_dir: /go/src/ants
    environment:
      - GO111MODULE=on
    entrypoint: 'sh init.sh'

  node:
    image: node:10.13.0-alpine
    volumes:
      - ./front:/app
      - ./static:/static
    working_dir: /app
    command: "sh docker/entrypoint.sh"

  nginx:
    image: nginx
    volumes:
      - ./static:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 81:80